#!/bin/bash
#PBS -l nodes=4:ppn=16
#PBS -l walltime=30:00
#PBS -N sassinaTest
#PBS -M lynchve@ornl.gov
#PBS -V

cd $PBS_O_WORKDIR
mkdir toppar
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/toppar/crd.md18_vmd_autopsf.pdb  toppar
cp ~/$NAMD_DIR/production01.dcd  production_single.dcd
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/db*.xml .
cp -R /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/database .
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/sassenaConf.xml .
/shared/openmpi/gcc/bin/mpirun -machinefile $PBS_NODEFILE -np 64 /shared/local/sassena/sassena-v1.4.1/builds/shared/sassena --config=sassenaConf.xml
