#!/bin/bash
#PBS -l nodes=2:ppn=16
#PBS -l walltime=59:00
#PBS -N namdTest

#module load /shared/etc/modulefiles/openmpi
#module load /shared/etc/modulefiles/namd/2.9-mpi_shared
MPIRUN=/shared/openmpi/gcc/bin/mpirun
NAMD=/shared/local/namd/NAMD_2.9_Linux-x86_64-mpi_shared/Linux-x86_64-g++/namd2

cd $PBS_O_WORKDIR
mkdir toppar
mv *psf toppar/Q32.psf
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/toppar/par_all27_prot_lipid.inp toppar
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/toppar/crd.md18_vmd_autopsf.pdb  toppar
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/production01.conf .
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/production00.restart.coor . 
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/production00.restart.vel . 
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q32/T290/production/production00.restart.xsc . 
$MPIRUN -machinefile $PBS_NODEFILE -np 32 $NAMD production01.conf > production01_eq_32cores.log
