#!/bin/bash
#PBS -l nodes=12:ppn=16
#PBS -l walltime=4:00:00
#PBS -N namdTest

#module load /shared/etc/modulefiles/openmpi
#module load /shared/etc/modulefiles/namd/2.9-mpi_shared
MPIRUN=/shared/openmpi/gcc/bin/mpirun
NAMD=/shared/local/namd/NAMD_2.9_Linux-x86_64-mpi_shared/Linux-x86_64-g++/namd2

cd $PBS_O_WORKDIR
mkdir toppar
mv *psf toppar/Q42.psf
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/toppar/par_all27_prot_lipid.inp toppar
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/toppar/crd.md18_vmd_autopsf.pdb  toppar
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/T290/production/production_single.conf .
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/T290/production/production00.restart.coor . 
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/T290/production/production00.restart.vel . 
cp /data/jbq/projects/research/LiCl/watBox30/Hq.II/Q42/T290/production/production00.restart.xsc . 
$MPIRUN -machinefile $PBS_NODEFILE -np 192 $NAMD production_single.conf > production_single_192cores.log
while [ $? -ne 0 ] ; do
    $MPIRUN -machinefile $PBS_NODEFILE -np 128 $NAMD production_single.conf > production_single_192cores.log
done
